# Generated by Django 4.2.1 on 2023-05-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_newuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
